"""Backward-compatibility re-export facade.

All pipeline classes and factory functions have been moved to dedicated modules:

- :mod:`so101_rl.metric_pipeline`     — MetricStep, MetricPipeline, concrete metric steps
- :mod:`so101_rl.reward_pipeline`     — RewardStep, RewardPipeline, concrete reward steps
- :mod:`so101_rl.dr_pipeline`         — DRStep, DRPipeline, concrete DR steps
- :mod:`so101_rl.env_metric_pipeline` — EnvMetricStep, EnvMetricPipeline, concrete env-metric steps

Imports from ``so101_rl.env_pipeline`` continue to work unchanged.
"""

from __future__ import annotations


from so101_rl.metric_pipeline import (
    StepContext,
    MetricStep,
    MetricPipeline,
    GripperContactForceMagnitudeMetricStep,
    TableTouchedMetricStep,
    CubePosEEMetricStep,
    GripperCubeAlignmentMetricStep,
    CubePosGZMetricStep,
    CubeRot6DGZMetricStep,
    GripZoneCubeDistanceMetricStep,
    NormalizedGripZoneCubeDistanceMetricStep,
    CubeHeightWMetricStep,
    CubeLiftFractionMetricStep,
    IsSuccessLiftFractionTerminalMetricStep,
    IsCubeInGripPositionMetricStep,
    IsCubeGrippedMetricStep,
    CubeDistanceFromBaseMetricStep,
    IsCubeOutOfRangeMetricStep,
    ApproachPhaseMetricStep,
    GraspPhaseMetricStep,
    ApproachPhaseTerminalMetricStep,
    GraspPhaseTerminalMetricStep,
    ALL_METRIC_STEPS,
    KEY_OBS_DIMS,
    build_metric_pipeline,
)
from so101_rl.reward_pipeline import (
    RewardStep,
    TerminalRewardStep,
    RewardPipeline,
    DistanceRewardStep,
    GripCubeRewardStep,
    LiftCubeRewardStep,
    GripperCubeAlignmentRewardStep,
    CloseGripperRewardStep,
    ActionRewardStep,
    EELinearSpeedRewardStep,
    JointSpeedRewardStep,
    SuccessLiftFractionTerminalRewardStep,
    SafetyTouchTableTerminalRewardStep,
    SafetyTouchTableRewardStep,
    CubeOutOfRangeTerminalRewardStep,
    ApproachPhaseTerminalRewardStep,
    GraspPhaseTerminalRewardStep,
    ApproachDistanceRewardStep,
    ApproachAlignmentRewardStep,
    ApproachGripperPoseRewardStep,
    ApproachPhaseRewardStep,
    AvoidBumpingCubeRewardStep,
    GraspPhaseRewardStep,
    WristRollPoseRewardStep,
    build_reward_pipeline,
    validate_gate_metrics,
)
from so101_rl.dr_pipeline import (
    DRContext,
    DRStep,
    DRPipeline,
    CubeColorDRStep,
    CubeSizeDRStep,
    CubePositionDRStep,
    CameraPoseDRStep,
    WorldLightingDRStep,
    EnvLightingDRStep,
    GroundMaterialDRStep,
    DistractorsDRStep,
    build_dr_pipeline,
)
from so101_rl.env_metric_pipeline import (
    EnvMetricStep,
    EnvMetricPipeline,
    CubeDimsEnvMetricStep,
    GripZoneOffsetEnvMetricStep,
    ALL_ENV_METRIC_STEPS,
    build_env_metric_pipeline,
)

__all__ = [
    # Contexts
    "StepContext",
    "DRContext",
    # Metric pipeline
    "MetricStep",
    "MetricPipeline",
    "GripperContactForceMagnitudeMetricStep",
    "TableTouchedMetricStep",
    "CubePosEEMetricStep",
    "GripperCubeAlignmentMetricStep",
    "CubePosGZMetricStep",
    "CubeRot6DGZMetricStep",
    "GripZoneCubeDistanceMetricStep",
    "NormalizedGripZoneCubeDistanceMetricStep",
    "CubeHeightWMetricStep",
    "CubeLiftFractionMetricStep",
    "IsSuccessLiftFractionTerminalMetricStep",
    "IsCubeInGripPositionMetricStep",
    "IsCubeGrippedMetricStep",
    "CubeDistanceFromBaseMetricStep",
    "IsCubeOutOfRangeMetricStep",
    "ApproachPhaseMetricStep",
    "GraspPhaseMetricStep",
    "ApproachPhaseTerminalMetricStep",
    "GraspPhaseTerminalMetricStep",
    "ALL_METRIC_STEPS",
    "KEY_OBS_DIMS",
    "build_metric_pipeline",
    # Reward pipeline
    "RewardStep",
    "TerminalRewardStep",
    "RewardPipeline",
    "DistanceRewardStep",
    "GripCubeRewardStep",
    "LiftCubeRewardStep",
    "GripperCubeAlignmentRewardStep",
    "CloseGripperRewardStep",
    "ActionRewardStep",
    "EELinearSpeedRewardStep",
    "JointSpeedRewardStep",
    "SuccessLiftFractionTerminalRewardStep",
    "SafetyTouchTableTerminalRewardStep",
    "SafetyTouchTableRewardStep",
    "CubeOutOfRangeTerminalRewardStep",
    "ApproachPhaseTerminalRewardStep",
    "GraspPhaseTerminalRewardStep",
    "ApproachDistanceRewardStep",
    "ApproachAlignmentRewardStep",
    "ApproachGripperPoseRewardStep",
    "ApproachPhaseRewardStep",
    "AvoidBumpingCubeRewardStep",
    "GraspPhaseRewardStep",
    "WristRollPoseRewardStep",
    "build_reward_pipeline",
    "validate_gate_metrics",
    # DR pipeline
    "DRStep",
    "DRPipeline",
    "CubeColorDRStep",
    "CubeSizeDRStep",
    "CubePositionDRStep",
    "CameraPoseDRStep",
    "WorldLightingDRStep",
    "EnvLightingDRStep",
    "GroundMaterialDRStep",
    "DistractorsDRStep",
    "build_dr_pipeline",
    # EnvMetric pipeline
    "EnvMetricStep",
    "EnvMetricPipeline",
    "CubeDimsEnvMetricStep",
    "GripZoneOffsetEnvMetricStep",
    "ALL_ENV_METRIC_STEPS",
    "build_env_metric_pipeline",
]
